### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by sbrockhaus** [PascalKieslich/mousetrap#1]
Just a small note on the documentation:

Line 
https://github.com/PascalKieslich/mousetrap/blob/01e170be8c2b249ae4ee90efbd0a09bc486e307e/R/mousetrap.R#L64
is 
`#'   \link{mt_sample_entropy}	calculates the initial movement angle.`
but I think it should be 
`#'   \link{mt_movement_angle}	calculates the initial movement angle.`

**Comment by PascalKieslich** [comment]
Just fixed it - thanks for pointing it out!
