### ISSUE TITLE
Sample Entropy R Calculation

### ISSUE THREAD

**Issue by Freihaut** [PascalKieslich/mousetrap#16]
I have been playing around with the mousetrap package to validate my mouse feature calculations in Python and I noticed that my sample_entropy function produces different results for calculating the sample entropy of x-position difference values for 6 trials than the mt_sample_entropy function. This seemed weird to me because I actually translated your `sample_entropy(x, m, r)` function into Python and was able to produce equal results for tests with different example vectors as inputs.

Looking more closely at the mt_sample_entropy function, I found that the difference between our approaches is that you calculate r using the standard deviation of the x-position difference data across all trials `r <- 0.2 * stats::sd(diff(t(trajectories[, , dimension])), na.rm = TRUE)` and I calculated separate r-values for each individual trial using the x-position difference data of the target trial only (which I find more intuitive). What is the rationale behind your approach (or is it a potential bug) and do you see an obvious shortcoming of my approach? I also read through the references you mentioned, but didn't find them very explicit in their explanation about the sample entropy calculations. Hehman et al. (2015) write in their supplementary files: _Recommended tolerance r is the standard deviation of x-shifts (Δx) across conditions_  Was this the reasoning for your approach? What would you recommend if each trial represents a "different" condition or is independent of each other?

**Comment by PascalKieslich** [comment]
Hi there,

that's a good point! I'll try to address it in several steps:

**1) Current implementation**

Yes, the implementation is as you describe it ("you calculate r using the standard deviation of the x-position difference data across all trials") and as intended (i.e., not a bug).

**2) Rationale behind it**

I tried to implement sample entropy like Hehman et al. (2015) described it. I agree with you that the description in the paper is not very explicit "... within a tolerance of .2 multiplied by the standard deviation of the x-shifts (the method employed
in our Python script in the Supplementary Material)" (p. 394). But, as you pointed out, this becomes more clear in the supplementary material ("Recommended tolerance r is the standard deviation of x-shifts (Δx) across conditions"). They also provide a link to a Python script within the supplementary material (https://github.com/rystoli/psychtools/blob/master/MT/SampEn.py). Unfortunately, this file does not seem to be online anymore but back in the day, when I implemented the function, I downloaded their script and this included an example code which, to my understanding, makes it explicit that they intended the SD to be computed across all trials:

```
#make fake test trajectories: 
#typical = sort([randint(0,150)*.01 for i in xrange(101)])
#atypical = sort([randint(0,150)*.01 for i in xrange(101)])
#sample call: SampEn(typical,3,.2*std(xshifts(typical)+xshifts(atypical)))
```
**3) Which approach is better?**

To be honest, I don't have a strong opinion on that as I never really used sample entropy in my own research projects (when I was still doing research). However, I believe that the approach that you describe has one drawback in that the sample entropy values are less comparable between trials if you vary the tolerance value (r) between trials. I see that it could make sense to compute the SD per trial, but maybe one could then average the SD values across trials in a second step and use this average SD as the tolerance value for all trials?

Best,

Pascal

**Comment by Freihaut** [comment]
Thank you for the thorough explanation. I really appreciate it!
I understand your concern about the potential problems of comparing sample entropy values from trials with different r-tresholds, thanks for highlighting it. After looking at sample_entropy for some now, I think that it is a less straightforward to interpret parameter (with many tuning options), which also produces NaN-values or Inf-values for some trials. So I might stick with x- & y-flips, angles and straight line deviations for potential movement-accuracy measures of a simple point-and-click task.
