### ISSUE TITLE
make it available in python as well

### ISSUE THREAD

**Issue by pranavnerurkar** [PascalKieslich/mousetrap#19]

**Comment by PascalKieslich** [comment]
Thank you for the suggestion. Although having a Python version of `mousetrap` sounds great, I don't have the resources  to develop one. Note that there is the [reticulate package](https://rstudio.github.io/reticulate/) that allows you to call Python from R, so you could do a first processing of the mouse-tracking data in R using `mousetrap` and then use Python functions on the processed data, in case this is something that helps in your application
