### ISSUE TITLE
vectorize the function point_to_line() for time speed up

### ISSUE THREAD

**Issue by sbrockhaus** [PascalKieslich/mousetrap#2]
To speed up the computation of the idealized line by the function `points_on_ideal()`, I propose to vectorize the function `point_to_line()` such that the argument `P0` expects a matrix of points and not just a single point. 

A small benchmark on computation times shows that the time is reduced drastically. On my machine the mean computation time for an example with 1000 observations can be reduced from about 1400 to 100 microseconds. 

As the functions `points_on_ideal()` and `point_to_line()` are both internal, it should be easy to replace `point_to_line()` by the vectorized version and keep everything else as is.  

Attached you find such a vectorized version of  `point_to_line()`, with some code for benchmarking (R-Code as .txt as .R files cannot be uploaded here). 

Best, 
Sarah

[vectorize_point_to_line.txt](https://github.com/PascalKieslich/mousetrap/files/381211/vectorize_point_to_line.txt)

**Comment by sbrockhaus** [comment]
see pull request https://github.com/PascalKieslich/mousetrap/pull/3 for proposed changes on the package

**Comment by PascalKieslich** [comment]
Thanks, Sarah, for the suggestion, your implementation, and the benchmark! Just accepted the changes you proposed.
