### ISSUE TITLE
reshape data in long format to data in mousetrap format as array 

### ISSUE THREAD

**Issue by sbrockhaus** [PascalKieslich/mousetrap#4]
This is a general question on whether the mousetrap package already conains the following functionality. I convert a mousetrap-object into long format, add one or several new variables to the long data and then I would like to transform the data back to mousetrap format. Consider the following example code:  

```javascript
library(mousetrap)
## example from package 
mt_example <- mt_import_mousetrap(mt_example_raw)

## reshape data into long format 
tr <- mt_reshape(data = mt_example, use = "trajectories", use2 = "data", 
                 use2_variables = c("Condition"), 
                 aggregate = FALSE) 

## add a new fancy variable 
tr$new_var <- rnorm(nrow(tr))

## now reshape back to mousetrap object like mt_example?
?
```
Is there a possibility to reshape `tr ` back to a mousetrap object like `mt_example`, where `new_var` is part of `trajectories` like `"timestamps" "xpos" "ypos"`?

**Comment by PascalKieslich** [comment]
Thanks for the question/suggestion. Data in long format (which results in your example from using mt_reshape) can be imported using mt_import_long.

However, thanks for pointing out the issue with importing newly created variables. So far, mt_import_long has not supported custom variables. However, I have changed the structure of the function so it accepts any variable. In doing so, I removed all specific label arguments and introduced the new mt_labels argument. This is available now on GitHub and will be included in the next release. 

Regarding your example, the solution would look like this:

```r
mt_data <- mt_import_long(tr,
  mt_labels= c(timestamps="timestamps", xpos="xpos", ypos="ypos", new_var="new_var"))
```
